/**
 * GENERATED by scripts/backtest/csv-replay.ts — do not edit by hand.
 * Aggregate-only football-data.co.uk replay summary. No production data touched.
 */
import type { HistoricalCsvSeed } from './historical-csv-seed';

export const HISTORICAL_CSV_SEED: HistoricalCsvSeed = {
  "generatedAt": "2026-06-15T21:13:28.208Z",
  "dataset": {
    "files": 149,
    "matchesTotal": 108375,
    "matchesWithReference": 101051,
    "leagues": 38,
    "seasons": 15,
    "dateRange": "2012-03-02 → 2026-06-13",
    "prematchMatches": 41493,
    "closingOnlyMatches": 59558
  },
  "models": {
    "LEGACY": {
      "matchesProcessed": 101051,
      "alerts": 5500,
      "wins": 2081,
      "losses": 3419,
      "pushes": 0,
      "winRatePct": 37.84,
      "avgOdds": 2.531,
      "avgEdgePct": 7.24,
      "roiPct": -6,
      "profitUnits": -329.82
    },
    "PINNACLE_LED": {
      "matchesProcessed": 101051,
      "alerts": 427,
      "wins": 191,
      "losses": 236,
      "pushes": 0,
      "winRatePct": 44.73,
      "avgOdds": 2.441,
      "avgEdgePct": 6.92,
      "roiPct": 5.41,
      "profitUnits": 23.11
    },
    "LOW_ODDS_LEGACY": {
      "matchesProcessed": 101051,
      "alerts": 3276,
      "wins": 1673,
      "losses": 1603,
      "pushes": 0,
      "winRatePct": 51.07,
      "avgOdds": 1.915,
      "avgEdgePct": 3.76,
      "roiPct": -3.77,
      "profitUnits": -123.52
    },
    "LOW_ODDS_PINNACLE_LED": {
      "matchesProcessed": 101051,
      "alerts": 49,
      "wins": 32,
      "losses": 17,
      "pushes": 0,
      "winRatePct": 65.31,
      "avgOdds": 1.739,
      "avgEdgePct": 2.59,
      "roiPct": 13.45,
      "profitUnits": 6.59
    },
    "SHARP_FINAL": {
      "matchesProcessed": 101051,
      "alerts": 53,
      "wins": 23,
      "losses": 30,
      "pushes": 0,
      "winRatePct": 43.4,
      "avgOdds": 2.498,
      "avgEdgePct": 5.96,
      "roiPct": 1.23,
      "profitUnits": 0.65
    },
    "SHARP_FINAL_LOW": {
      "matchesProcessed": 101051,
      "alerts": 12,
      "wins": 6,
      "losses": 6,
      "pushes": 0,
      "winRatePct": 50,
      "avgOdds": 1.722,
      "avgEdgePct": 2.56,
      "roiPct": -13.58,
      "profitUnits": -1.63
    },
    "SHARP_FINAL_V2": {
      "matchesProcessed": 101051,
      "alerts": 414,
      "wins": 188,
      "losses": 226,
      "pushes": 0,
      "winRatePct": 45.41,
      "avgOdds": 2.429,
      "avgEdgePct": 6.81,
      "roiPct": 5.91,
      "profitUnits": 24.45
    },
    "SHARP_FINAL_LOW_V2": {
      "matchesProcessed": 101051,
      "alerts": 53,
      "wins": 33,
      "losses": 20,
      "pushes": 0,
      "winRatePct": 62.26,
      "avgOdds": 1.726,
      "avgEdgePct": 2.59,
      "roiPct": 7.57,
      "profitUnits": 4.01
    },
    "LEGACY_QUALITY": {
      "matchesProcessed": 101051,
      "alerts": 5500,
      "wins": 2081,
      "losses": 3419,
      "pushes": 0,
      "winRatePct": 37.84,
      "avgOdds": 2.531,
      "avgEdgePct": 7.24,
      "roiPct": -6,
      "profitUnits": -329.82
    }
  },
  "modelsPrematch": {
    "LEGACY": {
      "matchesProcessed": 41493,
      "alerts": 5468,
      "wins": 2069,
      "losses": 3399,
      "pushes": 0,
      "winRatePct": 37.84,
      "avgOdds": 2.532,
      "avgEdgePct": 7.23,
      "roiPct": -5.93,
      "profitUnits": -324.43
    },
    "PINNACLE_LED": {
      "matchesProcessed": 41493,
      "alerts": 419,
      "wins": 186,
      "losses": 233,
      "pushes": 0,
      "winRatePct": 44.39,
      "avgOdds": 2.445,
      "avgEdgePct": 6.88,
      "roiPct": 4.77,
      "profitUnits": 20
    },
    "LOW_ODDS_LEGACY": {
      "matchesProcessed": 41493,
      "alerts": 3260,
      "wins": 1661,
      "losses": 1599,
      "pushes": 0,
      "winRatePct": 50.95,
      "avgOdds": 1.916,
      "avgEdgePct": 3.76,
      "roiPct": -3.98,
      "profitUnits": -129.79
    },
    "LOW_ODDS_PINNACLE_LED": {
      "matchesProcessed": 41493,
      "alerts": 49,
      "wins": 32,
      "losses": 17,
      "pushes": 0,
      "winRatePct": 65.31,
      "avgOdds": 1.739,
      "avgEdgePct": 2.59,
      "roiPct": 13.45,
      "profitUnits": 6.59
    },
    "SHARP_FINAL": {
      "matchesProcessed": 41493,
      "alerts": 53,
      "wins": 23,
      "losses": 30,
      "pushes": 0,
      "winRatePct": 43.4,
      "avgOdds": 2.498,
      "avgEdgePct": 5.96,
      "roiPct": 1.23,
      "profitUnits": 0.65
    },
    "SHARP_FINAL_LOW": {
      "matchesProcessed": 41493,
      "alerts": 12,
      "wins": 6,
      "losses": 6,
      "pushes": 0,
      "winRatePct": 50,
      "avgOdds": 1.722,
      "avgEdgePct": 2.56,
      "roiPct": -13.58,
      "profitUnits": -1.63
    },
    "SHARP_FINAL_V2": {
      "matchesProcessed": 41493,
      "alerts": 407,
      "wins": 184,
      "losses": 223,
      "pushes": 0,
      "winRatePct": 45.21,
      "avgOdds": 2.432,
      "avgEdgePct": 6.76,
      "roiPct": 5.61,
      "profitUnits": 22.82
    },
    "SHARP_FINAL_LOW_V2": {
      "matchesProcessed": 41493,
      "alerts": 53,
      "wins": 33,
      "losses": 20,
      "pushes": 0,
      "winRatePct": 62.26,
      "avgOdds": 1.726,
      "avgEdgePct": 2.59,
      "roiPct": 7.57,
      "profitUnits": 4.01
    },
    "LEGACY_QUALITY": {
      "matchesProcessed": 41493,
      "alerts": 5468,
      "wins": 2069,
      "losses": 3399,
      "pushes": 0,
      "winRatePct": 37.84,
      "avgOdds": 2.532,
      "avgEdgePct": 7.23,
      "roiPct": -5.93,
      "profitUnits": -324.43
    }
  }
};
