export type { OddspapiVideogame, OddspapiMatchOdds, OddspapiOutcome, OddspapiBookmaker, GetOddsForGameResponse } from './types';
export type { OddspapiClientConfig } from './oddspapi.config';
export { ODDSPAPI_DEFAULTS } from './oddspapi.config';
export type { OddspapiClient } from './oddspapi.client';
export { DefaultOddspapiClient } from './oddspapi.client';
export { ResilientOddspapiClient } from './oddspapi.resilient-client';
export { OddspapiQuotaTracker } from './quota.tracker';
export { createOddspapiClient } from './oddspapi.factory';
export { PANDASCORE_TO_ODDSPAPI_KEY, ODDSPAPI_SPORT_IDS, ODDSPAPI_H2H_MARKET_IDS } from './game-key.map';
export { TEAM_ALIASES, resolveAlias, normalizeTeamName } from './team-aliases';